[build]
command = "npm install --legacy-peer-deps && npm run build"
functions = "api"
publish = ".next/static"

[build.environment]
NODE_ENV = "production"
NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
