[build]
command = "npm install --include=dev && npm run build"
functions = "api"
publish = ".next"

[build.environment]
NODE_ENV = "production"
SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_URL,OPENAI_MODEL"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
