[build]
command = "npm install --include=dev && npm run build"
functions = "api"
publish = ".next"

[build.environment]
NODE_ENV = "production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
